remote_theme: daattali/beautiful-jekyll

# Title Website and Author
title: Praktikum Web Lanjutan
author: Aufa Billah

# Navbar
navbar-links:
  About Me: "aboutme"
  Authors: "https://aufaroot18.github.io/"

# Avatar Icon
avatar: "/assets/img/icon.png"
round-avatar: true
